### PR TITLE
Cocotb updates 

### PR DESCRIPTION
**Pull request by M0stafaRady**
- Adding initial cocotb tests for testing the chain and and gate design 
- Adding power connection to the fpga RTL

### CODE REVIEW

**Review by mo-hosni — APPROVED** [review]
Makes sense and does not introduce any PnR issues.

**Comment by M0stafaRady** [comment]
@marwaneltoukhy What do you mean by not running verification post synthesis ?

**Comment by marwaneltoukhy** [comment]
why aren't you running the verification on the gl netlist coming out of OpenLane?

**Comment by M0stafaRady** [comment]
We do

**Comment by marwaneltoukhy** [comment]
Then why are you editing these files? The gl netlist coming out of OpenLane is already powered.

**Comment by M0stafaRady** [comment]
This is for the RTL files which contain sky130 cells

**Comment by marwaneltoukhy** [comment]
These aren't RTL files, these are netlists as well. That's why I am asking why aren't you just using the ones coming out of OpenLane.

**Comment by M0stafaRady** [comment]
These are readable netlist so it's easier to debug them compared with what Openlane provided.

**Comment by M0stafaRady** [comment]
I checked these changes more than one time but I will really appreciate if someone else also have a look to make sure the script have not corrupted anything.

**Review by marwaneltoukhy — APPROVED** [review]

**Pull request merged**
